### ISSUE TITLE
最終APが正しくない場合がある

### ISSUE THREAD

**Issue by kanata3249** [antenna-three/fgoapcalc#1]
以下のケースで最終APがおかしいようです。

1. 現在AP36からAP15クエストを12周
  聖晶石-1 AP144になる
2. 現在AP36からAP15クエストを1周
  聖晶石±0 AP165になる

( 絆確認する手間が大幅に減らせそうです。ありがとうございます )

**Comment by antenna-three** [comment]
報告ありがとうございます。
(現在AP-合計消費AP) が最大APの倍数や正の数だった場合に最終APがおかしくなる不具合でした。
聖晶石の消費数は正しかったので、計算した最終APに対して最大APの剰余を取るようにしました。
報告いただいた両方のケースに対して正しい結果を返すようになりました。
